### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by adamjsturge** [containrrr/shoutrrr-action#75]
**Describe the bug**
Unable to run shoutrrr on macos pipelines

**To Reproduce**

```yml
name: Test Action
on:
  pull_request:
  workflow_dispatch:

jobs:
  testjob:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify on Fail
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.SHOUTRRR_URL }}
          title: "Test Action"
          message: "This action could work"
```

**Expected behavior**
Would like it not to crash and work on macos
